using System;
using System.Collections.Generic;
using System.Linq;
using AlignmentReforge.Domain;
using static AlignmentReforge.Geometry.GeometryMath;

namespace AlignmentReforge.Geometry;

/// <summary>
/// Case 2 solver — interval-sampled centreline coordinates.
///
/// Key insight
/// ───────────
/// Every sample point was generated by Civil 3D from an exact alignment object.
/// It lies EXACTLY on the designed geometry.  There is no noise.  The curvature
/// profile of noiseless data is a perfect trapezoid:
///
///   Tangent    κ = 0
///   Spiral in  κ = s/(R·Ls)          linear ramp  0 → 1/R
///   Arc        κ = 1/R               constant plateau
///   Spiral out κ = (Ls−s)/(R·Ls)    linear ramp  1/R → 0
///   Tangent    κ = 0
///
/// Algorithm
/// ─────────
/// 1.  Compute signed osculating curvature at every interior vertex (exact
///     3-point circumscribed-circle formula — not finite difference).
///
/// 2.  Detect the plateau of each curve zone:
///       - Find contiguous runs of same-sign curvature above noise floor.
///       - Identify the plateau (constant-κ region = the arc).
///       - The plateau height gives 1/R → R exactly (median of plateau values).
///
/// 3.  Locate the four zone boundaries by linear interpolation on the ramps:
///       - TS: where the rising ramp departs zero (back-extrapolate ramp line to κ=0)
///       - SC: where the ramp reaches the plateau (ramp line to κ=1/R)
///       - CS: where the plateau drops off the arc (trailing ramp line to κ=1/R)
///       - ST: where the trailing ramp reaches zero (extrapolate to κ=0)
///     All four are sub-interval-accurate regardless of sample spacing.
///
/// 4.  Read Ls_in, Ls_out, arc_length directly from the station differences.
///
/// 5.  Membership test every point against the clothoid offset equation.
///     For clean Civil 3D data this will be satisfied to < 1 mm.
///     Failure → zone flagged inconclusive (non-standard geometry).
///
/// This is a READ, not a FIT.  The result is deterministic and unique
/// for any valid clothoid alignment at any sample interval ≥ 1 m.
/// </summary>
internal static class Case2Solver
{
    // ── public entry ─────────────────────────────────────────────────────────

    internal static List<(SolvedCurve? curve, InconclusiveZone? inconclusive)> SolveAll(
        IReadOnlyList<Vertex> vertices,
        double[] stations,
        SolverSettings s)
    {
        var kappa = ComputeCurvatureProfile(vertices);
        var groups = DetectCurveGroups(kappa, stations, s);

        var results = new List<(SolvedCurve?, InconclusiveZone?)>();
        var zoneNum = 0;

        foreach (var g in groups)
        {
            zoneNum++;
            try
            {
                var curve = SolveGroup(vertices, stations, kappa, g, zoneNum, s);
                results.Add((curve, null));
            }
            catch (System.Exception ex)
            {
                // Identify the anchor vertices closest to the group endpoints
                var tsV = vertices[g.StartIndex];
                var stV = vertices[g.EndIndex];
                results.Add((null, new InconclusiveZone(zoneNum, ex.Message, tsV, stV)));
            }
        }

        return results;
    }

    // ── curvature profile ─────────────────────────────────────────────────────

    /// <summary>
    /// Exact signed osculating curvature at each interior vertex.
    /// End vertices get the curvature of their nearest interior neighbour.
    /// </summary>
    internal static double[] ComputeCurvatureProfile(IReadOnlyList<Vertex> v)
    {
        var n = v.Count;
        var k = new double[n];
        for (var i = 1; i < n - 1; i++)
            k[i] = OsculatingCurvature(v[i - 1].Position, v[i].Position, v[i + 1].Position);
        k[0]     = k[1];
        k[n - 1] = k[n - 2];
        return k;
    }

    // ── group detection ───────────────────────────────────────────────────────

    private sealed record CurveGroup(
        int Sign,          // +1 right, −1 left
        int StartIndex,    // first vertex with |κ| > noise
        int EndIndex,      // last vertex with |κ| > noise
        int PlateauStart,  // first vertex in plateau
        int PlateauEnd,    // last vertex in plateau
        double PlateauKappa); // 1/R

    private static List<CurveGroup> DetectCurveGroups(
        double[] kappa, double[] stations, SolverSettings s)
    {
        var n = kappa.Length;
        var absK = kappa.Select(Math.Abs).ToArray();
        var noiseFloor = s.CurvatureZeroTolerance;

        // Find all contiguous non-zero-curvature runs
        var groups = new List<CurveGroup>();
        var i = 1;
        while (i < n - 1)
        {
            if (absK[i] <= noiseFloor) { i++; continue; }

            var sign = Math.Sign(kappa[i]);
            var start = i;
            while (i < n - 1 && Math.Sign(kappa[i]) == sign && absK[i] > noiseFloor) i++;
            var end = i - 1;

            if (end - start < 2) continue;   // too short

            // Find the plateau inside this run: region where κ is roughly constant
            var (pStart, pEnd, plateauK) = FindPlateau(kappa, stations, start, end, sign, s);
            if (pStart < 0) continue;         // no stable plateau → not a standard curve

            groups.Add(new CurveGroup(sign, start, end, pStart, pEnd, plateauK));
        }

        return groups;
    }

    private static (int start, int end, double kappa) FindPlateau(
    double[] kappa, double[] stations, int from, int to, int sign, SolverSettings s)
    {
        // Plateau = arc region where curvature is genuinely flat.
        // Criterion: finite difference |κ[i+1] - κ[i-1]| / κ_peak < 0.01
        // Universally valid — on arc dκ/ds = 0 exactly,
        // on spiral dκ/ds = 1/(R·Ls) which is always nonzero and detectable.

        var peak = 0.0;
        for (var i = from; i <= to; i++)
            peak = Math.Max(peak, Math.Abs(kappa[i]));

        if (peak <= s.CurvatureZeroTolerance) return (-1, -1, 0);

        var fdThreshold = peak * 0.01;

        var pStart = -1; var pEnd = -1;
        for (var i = from + 1; i <= to - 1; i++)
        {
            var fd = Math.Abs(kappa[i + 1] - kappa[i - 1]);
            if (fd < fdThreshold && Math.Abs(kappa[i]) > peak * 0.90)
            {
                if (pStart < 0) pStart = i;
                pEnd = i;
            }
        }

        if (pStart < 0 || pEnd <= pStart) return (-1, -1, 0);

        var plateauVals = Enumerable.Range(pStart, pEnd - pStart + 1)
                                    .Select(idx => kappa[idx] * sign)
                                    .ToArray();
        var plateauK = Median(plateauVals);

        return (pStart, pEnd, plateauK);
    }

    // ── solve one group ───────────────────────────────────────────────────────

    private static SolvedCurve SolveGroup(
        IReadOnlyList<Vertex> vertices,
        double[] stations,
        double[] kappa,
        CurveGroup g,
        int zoneNum,
        SolverSettings s)
    {
        // ── Step 1: R directly from plateau ───────────────────────────────

        var R = 1.0 / g.PlateauKappa;
        if (R <= 0 || double.IsInfinity(R))
            throw new InvalidOperationException("Plateau curvature yields non-positive R.");

        // ── Step 2: locate the four boundaries by ramp interpolation ──────

        // Rising ramp: indices from g.StartIndex to g.PlateauStart - 1.
        // We fit a line through the ramp κ values vs station, then solve for
        // the stations where the line = 0 (TS) and where it = plateauK (SC).
        // Exclude the plateau-start point itself: it is already at plateau level
        // and would corrupt the ramp slope estimate if included.

        var tsStation = InterpolateRampZero(
            kappa, stations, g.StartIndex, g.PlateauStart, g.Sign,
            g.PlateauKappa, fromStart: true);

        var scStation = InterpolateRampLevel(
            kappa, stations, g.StartIndex, g.PlateauStart, g.Sign,
            g.PlateauKappa, fromStart: true);

        // Trailing ramp: from g.PlateauEnd to g.EndIndex.

        var csStation = InterpolateRampLevel(
            kappa, stations, g.PlateauEnd, g.EndIndex, g.Sign,
            g.PlateauKappa, fromStart: false);

        var stStation = InterpolateRampZero(
            kappa, stations, g.PlateauEnd, g.EndIndex, g.Sign,
            g.PlateauKappa, fromStart: false);

        if (!(tsStation < scStation && scStation < csStation && csStation < stStation))
            throw new InvalidOperationException(
                $"Boundary interpolation produced invalid station order: " +
                $"TS={tsStation:F3} SC={scStation:F3} CS={csStation:F3} ST={stStation:F3}");

        // ── Step 3: read Ls and arc_length directly ────────────────────────

        var lsIn = scStation - tsStation;
        var lsOut = stStation - csStation;
        var arcLen = csStation - scStation;

        if (lsIn <= 0 || lsOut <= 0 || arcLen < 0)
            throw new InvalidOperationException("Non-positive spiral or arc length from boundary interpolation.");

        // ── Step 4: derive all parameters ─────────────────────────────────

        var dir = g.Sign > 0 ? TurnDirection.Right : TurnDirection.Left;
        var thetaInRad = lsIn / (2.0 * R);
        var thetaOutRad = lsOut / (2.0 * R);
        var arcAngleRad = arcLen / R;
        var deltaDeg = Rad2Deg(thetaInRad + arcAngleRad + thetaOutRad);
        var aIn = Math.Sqrt(R * lsIn);
        var aOut = Math.Sqrt(R * lsOut);
        var lsSymm = (lsIn + lsOut) / 2.0;
        var aSymm = Math.Sqrt(R * lsSymm);

        // ── Step 5: interpolate actual XY positions of TS, SC, CS, ST ─────

        var tsPos = PointAtStation(vertices, stations, tsStation);
        var scPos = PointAtStation(vertices, stations, scStation);
        var csPos = PointAtStation(vertices, stations, csStation);
        var stPos = PointAtStation(vertices, stations, stStation);

        var tsV = new Vertex(FindNearestIndex(stations, tsStation), tsPos, VertexHint.Tangent);
        var scV = new Vertex(FindNearestIndex(stations, scStation), scPos, VertexHint.Curve);
        var csV = new Vertex(FindNearestIndex(stations, csStation), csPos, VertexHint.Curve);
        var stV = new Vertex(FindNearestIndex(stations, stStation), stPos, VertexHint.Tangent);

        // Entry and exit tangent bearings: from the tangent segment before TS / after ST
        var entryBearing = TangentBearingBefore(vertices, stations, tsStation, s);
        var exitBearing = TangentBearingAfter(vertices, stations, stStation, s);

        // Arc chord check
        var arcChord = Distance(scPos, csPos);
        var chordExp = 2.0 * R * Math.Sin(arcAngleRad / 2.0);
        var chordResid = arcChord - chordExp;

        var center = ArcCenter(scPos, csPos, R, dir);

        // ── Step 6: membership test ────────────────────────────────────────

        var spiralInVerts = SliceVertices(vertices, stations, tsStation, scStation, VertexHint.Curve);
        var spiralOutVerts = SliceVertices(vertices, stations, csStation, stStation, VertexHint.Curve);

        var residIn = MembershipTest(spiralInVerts, tsV, entryBearing, (int)dir, R, lsIn);
        var residOut = MembershipTest(spiralOutVerts.Reverse().ToArray(),
                                      stV, NormDeg(exitBearing + 180.0), -(int)dir, R, lsOut);

        var allResid = residIn.Concat(residOut).ToArray();
        var rmsM = allResid.Length == 0
            ? 0.0
            : Math.Sqrt(allResid.Average(r => r.Residual * r.Residual));
        if (rmsM * 1000.0 > s.TrapezoidResidualErrorMm)
            throw new InvalidOperationException(
                $"Membership test RMS = {rmsM * 1000.0:F1} mm exceeds threshold " +
                $"{s.TrapezoidResidualErrorMm:F1} mm — geometry is not a standard Clothoid.");

        // Curvature-fit RMS in mm (for reporting; residual already in 1/m units)
        var kRms = Math.Sqrt(
            Enumerable.Range(g.StartIndex, g.EndIndex - g.StartIndex + 1)
                      .Select(idx =>
                      {
                          var expected = ModelCurvature(stations[idx], tsStation, scStation,
                                                        csStation, stStation, g.PlateauKappa * g.Sign);
                          var diff = kappa[idx] - expected;
                          return diff * diff;
                      }).Average());
        var curvatureFitRmsMm = kRms * R * R * 1000.0;   // convert κ-residual → offset mm

        // ── Assemble ───────────────────────────────────────────────────────

        return new SolvedCurve(
            CurveNumber: zoneNum,
            Direction: dir,
            Radius: R,
            SpiralLength: lsSymm,
            SpiralLengthIn: lsIn,
            SpiralLengthOut: lsOut,
            A: aSymm,
            AIn: aIn,
            AOut: aOut,
            DeltaDegrees: deltaDeg,
            ThetaSDegrees: Rad2Deg((thetaInRad + thetaOutRad) / 2.0),
            ThetaSInDegrees: Rad2Deg(thetaInRad),
            ThetaSOutDegrees: Rad2Deg(thetaOutRad),
            ArcAngleDegrees: Rad2Deg(arcAngleRad),
            ArcLength: arcLen,
            EntryBearing: entryBearing,
            ExitBearing: exitBearing,
            TS: tsV,
            SC: scV,
            CS: csV,
            ST: stV,
            StaTS: tsStation,
            StaSC: scStation,
            StaCS: csStation,
            StaST: stStation,
            ChordActual: arcChord,
            ChordExpected: chordExp,
            ChordResidual: chordResid,
            ArcCenter: center,
            MembershipRmsM: rmsM,
            MembershipResiduals: allResid,
            CurvatureFitRmsMm: curvatureFitRmsMm);
    }

    // ── ramp interpolation ────────────────────────────────────────────────────

    /// <summary>
    /// Fit a line through the ramp κ values and extrapolate to κ = 0.
    /// fromStart=true: extrapolate backward (find TS).
    /// fromStart=false: extrapolate forward (find ST).
    /// plateauKappa: plateau curvature (1/R); points at or above 95% of plateau
    /// are excluded — they are arc or arc-transition points, not ramp points.
    /// Falls back to endpoint station if fit is degenerate.
    /// </summary>
    private static double InterpolateRampZero(
        double[] kappa, double[] stations,
        int from, int to, int sign, double plateauKappa, bool fromStart)
    {
        // Transition-bias: the 3-point OsculatingCurvature at the first/last ramp
        // sample is biased because one neighbour lies on the zero-curvature tangent.
        // We prefer to exclude it, but if that leaves fewer than 2 points we fall
        // back to the unfiltered set — a mildly biased fit is better than a
        // single-endpoint fallback that guarantees a wrong answer.
        var biasCutoff = plateauKappa * 0.01;

        var xs = new List<double>(); var ys = new List<double>();
        var xsAll = new List<double>(); var ysAll = new List<double>();
        for (var i = from; i <= to; i++)
        {
            var kSigned = kappa[i] * sign;
            if (kSigned <= 0 || kSigned >= plateauKappa * 0.95) continue;
            xsAll.Add(stations[i]); ysAll.Add(kSigned);

            var biased = (fromStart && i > 0 && kappa[i - 1] * sign < biasCutoff)
                      || (!fromStart && i < kappa.Length - 1 && kappa[i + 1] * sign < biasCutoff);
            if (!biased) { xs.Add(stations[i]); ys.Add(kSigned); }
        }

        // Prefer bias-filtered fit; fall back to unfiltered when too few points survive.
        var (fitXs, fitYs) = xs.Count >= 2 ? (xs, ys) : (xsAll, ysAll);
        if (fitXs.Count < 2) return fromStart ? stations[from] : stations[to];
        var (ok, slope, intercept) = FitLine(fitXs, fitYs);
        if (!ok || Math.Abs(slope) < 1e-15) return fromStart ? stations[from] : stations[to];
        var station = -intercept / slope;   // κ = 0 → station = -b/m
        return Math.Clamp(station,
            stations[Math.Max(0, from - 1)],
            stations[Math.Min(stations.Length - 1, to + 1)]);
    }

    /// <summary>
    /// Fit a line through the ramp and solve for the station where κ = targetKappa.
    /// plateauKappa: plateau curvature (1/R); points at or above 95% of plateau
    /// are excluded for the same reason as in InterpolateRampZero.
    /// </summary>
    private static double InterpolateRampLevel(
        double[] kappa, double[] stations,
        int from, int to, int sign, double targetKappa, bool fromStart)
    {
        // Same bias-filter logic as InterpolateRampZero: prefer excluding biased
        // boundary samples, but fall back to the unfiltered set when fewer than
        // 2 clean points survive (coarse-interval data).
        var biasCutoff = targetKappa * 0.01;

        var xs = new List<double>(); var ys = new List<double>();
        var xsAll = new List<double>(); var ysAll = new List<double>();
        for (var i = from; i <= to; i++)
        {
            var kSigned = kappa[i] * sign;
            if (kSigned <= 0 || kSigned >= targetKappa * 0.95) continue;
            xsAll.Add(stations[i]); ysAll.Add(kSigned);

            var biased = (fromStart && i > 0 && kappa[i - 1] * sign < biasCutoff)
                      || (!fromStart && i < kappa.Length - 1 && kappa[i + 1] * sign < biasCutoff);
            if (!biased) { xs.Add(stations[i]); ys.Add(kSigned); }
        }

        var (fitXs, fitYs) = xs.Count >= 2 ? (xs, ys) : (xsAll, ysAll);
        if (fitXs.Count < 2) return fromStart ? stations[to] : stations[from];
        var (ok, slope, intercept) = FitLine(fitXs, fitYs);
        if (!ok || Math.Abs(slope) < 1e-15) return fromStart ? stations[to] : stations[from];
        var station = (targetKappa - intercept) / slope;
        return Math.Clamp(station,
            stations[Math.Max(0, from - 1)],
            stations[Math.Min(stations.Length - 1, to + 1)]);
    }

    // ── geometry helpers ──────────────────────────────────────────────────────

    private static Point2D PointAtStation(IReadOnlyList<Vertex> v, double[] st, double target)
    {
        if (target <= st[0]) return v[0].Position;
        if (target >= st[^1]) return v[^1].Position;
        var idx = FindSegment(st, target);
        var f = (target - st[idx]) / (st[idx + 1] - st[idx]);
        return new Point2D(
            v[idx].X + (v[idx + 1].X - v[idx].X) * f,
            v[idx].Y + (v[idx + 1].Y - v[idx].Y) * f);
    }

    private static int FindSegment(double[] st, double target)
    {
        for (var i = 0; i < st.Length - 1; i++)
            if (target <= st[i + 1]) return i;
        return st.Length - 2;
    }

    private static int FindNearestIndex(double[] st, double target)
    {
        var idx = FindSegment(st, target);
        return Math.Abs(st[idx] - target) <= Math.Abs(st[idx + 1] - target) ? idx : idx + 1;
    }

    private static double TangentBearingBefore(
        IReadOnlyList<Vertex> v, double[] st, double tsStation, SolverSettings s)
    {
        var seg = FindSegment(st, tsStation);
        for (var i = seg - 1; i >= Math.Max(0, seg - 1); i--)
        {
            if (st[i + 1] - st[i] >= s.NearZeroDistance)
                return Azimuth(v[i].Position, v[i + 1].Position);
        }
        return Azimuth(v[0].Position, v[Math.Min(1, v.Count - 1)].Position);
    }

    private static double TangentBearingAfter(
        IReadOnlyList<Vertex> v, double[] st, double stStation, SolverSettings s)
    {
        var seg = FindSegment(st, stStation) + 1;
        for (var i = seg; i <= Math.Min(v.Count - 2, seg); i++)
        {
            if (st[i + 1] - st[i] >= s.NearZeroDistance)
                return Azimuth(v[i].Position, v[i + 1].Position);
        }
        return Azimuth(v[Math.Max(0, v.Count - 2)].Position, v[^1].Position);
    }

    private static IReadOnlyList<Vertex> SliceVertices(
        IReadOnlyList<Vertex> v, double[] st, double from, double to, VertexHint hint)
    {
        var result = new List<Vertex>();
        for (var i = 0; i < v.Count; i++)
            if (st[i] >= from - 1e-6 && st[i] <= to + 1e-6)
                result.Add(v[i] with { Hint = hint });
        return result;
    }

    private static SpiralResidual[] MembershipTest(
        IReadOnlyList<Vertex> verts,
        Vertex anchor, double anchorBearingDeg, int sign,
        double R, double Ls)
    {
        var bRad = Deg2Rad(anchorBearingDeg);
        var tx = Math.Sin(bRad); var ty = Math.Cos(bRad);
        var px = ty * sign; var py = -tx * sign;
        return verts.Select(v =>
        {
            var dx = v.X - anchor.X; var dy = v.Y - anchor.Y;
            var sAlong = dx * tx + dy * ty;
            var measured = dx * px + dy * py;
            var expected = SpiralOffset(sAlong, R, Ls);
            return new SpiralResidual(v.Index, sAlong, measured, expected, measured - expected);
        }).ToArray();
    }

    private static double ModelCurvature(
        double station,
        double ts, double sc, double cs, double st,
        double signedPlateauK)
    {
        if (station <= ts || station >= st) return 0.0;
        if (station < sc) return signedPlateauK * (station - ts) / (sc - ts);
        if (station <= cs) return signedPlateauK;
        return signedPlateauK * (st - station) / (st - cs);
    }
}
